### ISSUE TITLE
v0.6 updates?

### ISSUE THREAD

**Issue by n6smith** [Aepelzen/AepelzensModules#16]
Any chance of a v0.6 build for your plugins?

**Comment by Aepelzen** [comment]
There are no precompiled binaries if that is what you are looking for. But the plugin is compatible with 0.6 (I just merged the 0.6 branch into the master branch), so you can build it yourself.

**Comment by n6smith** [comment]
Thank you! Your Quad Sequencer is one of those 'essential ' modules for me and therefore your work is very much appreciated! Do you have a means of taking a donation?

**Comment by phdsg** [comment]
getting a build error:
```
g++ -Wsuggest-override -std=c++11 -DSLUG="Aepelzens Modules" -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0dev -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/folder.cpp.o src/folder.cpp
src/folder.cpp:3:10: fatal error: samplerate.h: No such file or directory
 #include <samplerate.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [../../compile.mk:62: build/src/folder.cpp.o] Error 1
```

note that `libsamplerate` is not included in rack anymore. it got replaced with speex i think, so you have to either use that or include libsamplerate like the fundamental modules.

**Comment by n6smith** [comment]
I just got the Mac binary compiled for me.. Ill check if he had to do anything special.... as he didnt report any issues

**Comment by Aepelzen** [comment]
n6smith: Thank you for the kind offer,I appreciate that very much but donations are not neccessary.
Also, you most likely already have libsamplerate installed. That's why you had no issues during compiling.

phdsg: I know. I'm not yet sure about the best way to deal with this. I don't like the approach of building dependencies locally (that's what package managers are for), especially if you have to build the same libraries for multiple plugins (and I assume that most people already have libsamplerate). I'm currently busy with other stuff and don't know very much about Makefiles but I'm gonna check for alternative solutions, ideally a compromise where the system library is used if it is installed (like most programs do) or build locally if it isn't.

**Comment by phdsg** [comment]
haven't looked at what you're using `libsamplerate` for, but maybe speex (that's included in rack now) can do the same.
otherwise just copy the Makefile the fundamental/delay uses.

**Comment by Aepelzen** [comment]
I know about speex and will most likely get rid of libsamplerate at some point and use Racks samplerateConverter instead. But I'm already working on a new Module that needs another library so I will have to figure this out anyway.

**Comment by Aepelzen** [comment]
Hey n6smith, check out the new QuadSequencer. You might like it even more now (I hope)
