### ISSUE TITLE
quad seq mode control label

### ISSUE THREAD

**Issue by joopvdl** [Aepelzen/AepelzensModules#5]
For me, it would really help if the mode control on quad seq had would have some sort of labeling, so it will be a bit easer to choose the right mode.

**Comment by Aepelzen** [comment]
Panel design has been a pretty low priority so far (as you can probably tell), but this whill hopefully change soon. However I will probably not use the actual modes as labels as that would require a lot of space. But i will try to figure smth. out to make it easier to use, until than you have to read the manual ;)

**Comment by joopvdl** [comment]
I quite like the look, as it is.
Just a simple line and an abbreviation of the mode would be ok. Or an arrow or other symbol
You could also consider putting small lines at the button, and to make an overview in the empty area up right, where we (the user) could see the placement of the modes. If you understand what I mean.

**Comment by Aepelzen** [comment]
This took a while and it might still not be exactly what you were looking for but I made the Steps and Mode knobs snap to Integer values so it should be much easier to hit the right values (especially since there are only 5 modes).

I tried a label at some point (not released) and didn't really like it, so I think I will stay with this. What do you think? Does this solve your problem?

**Comment by joopvdl** [comment]
I would need a build to check that out, because I myself cannot do that.

**Comment by Aepelzen** [comment]
With the latest QuadSequencer update the panel got quite crowded so i guess the label idea is dead for now. I hope the snapping will be good enough.
